# Crate a secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: user-to-postgres
  POSTGRES_PASSWORD: password-to-postgres-user
  POSTGRES_DB: postgres